# Generated by Django 3.0.3 on 2020-05-07 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('media_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentCatalogDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('media_path', models.CharField(max_length=200)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.InstrumentCatalog')),
            ],
        ),
    ]
