# Generated by Django 3.0.3 on 2020-05-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_sliders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentcatalogdetail',
            name='instrument',
        ),
        migrations.AddField(
            model_name='instrumentcatalogdetail',
            name='instrument',
            field=models.ManyToManyField(to='index.InstrumentCatalog'),
        ),
    ]
