# Generated by Django 3.0.3 on 2020-05-11 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200511_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentcatalogdetail',
            name='instrument',
        ),
        migrations.CreateModel(
            name='InstrumentCatalogDetailIntermediary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.InstrumentCatalog')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.InstrumentCatalogDetail')),
            ],
        ),
    ]
