# Generated by Django 3.0.3 on 2020-05-11 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200511_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentcatalogdetailintermediary',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.InstrumentCatalogDetail'),
        ),
        migrations.AlterField(
            model_name='instrumentcatalogdetailintermediary',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.InstrumentCatalog'),
        ),
    ]
