# Generated by Django 3.0.3 on 2020-05-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20200511_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vendor_code', models.CharField(max_length=15)),
                ('price', models.CharField(max_length=10)),
                ('wholesale_var', models.CharField(max_length=3)),
                ('media_path', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='media_path',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
