# Generated by Django 3.0.3 on 2020-05-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20200513_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('media_path', models.ImageField(max_length=200, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Tools',
        ),
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='media_path',
            field=models.ImageField(max_length=200, upload_to='CatalogImg/'),
        ),
        migrations.AlterField(
            model_name='instrumentcatalogdetail',
            name='media_path',
            field=models.ImageField(max_length=200, upload_to='CatalogImg/'),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='media_path',
            field=models.ImageField(max_length=200, upload_to='SlidersImg/'),
        ),
    ]
