# Generated by Django 3.0.3 on 2020-05-18 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20200518_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vendor_code', models.CharField(max_length=15)),
                ('price', models.CharField(max_length=10)),
                ('wholesale_var', models.CharField(max_length=3)),
                ('media_path', models.ImageField(max_length=200, upload_to='ToolImg/')),
                ('amount', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=100)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.Companys')),
                ('detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.InstrumentCatalogDetail')),
                ('instrument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.InstrumentCatalog')),
            ],
        ),
    ]
