# Generated by Django 3.0.3 on 2020-05-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_lineup_toolslineup'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentcatalog',
            name='name_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='instrumentcatalogdetail',
            name='name_link',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
