# Generated by Django 3.0.3 on 2020-05-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20200520_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentcatalog',
            name='media_path',
            field=models.FileField(max_length=200, upload_to='CatalogImg/'),
        ),
        migrations.AlterField(
            model_name='instrumentcatalogdetail',
            name='media_path',
            field=models.FileField(max_length=200, upload_to='CatalogImg/'),
        ),
        migrations.AlterField(
            model_name='instrumentcatalogdetail',
            name='name_link',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
