# Generated by Django 3.0.3 on 2020-07-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20200521_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
